[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
build_src_filter = +<camera/>

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
build_src_filter = +<control/>